apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapicore-deployment
spec:
  selector:
    matchLabels:
      app: webapicore
  replicas: 1
  template:
    metadata:
      labels:
        app: webapicore
    spec:
      containers:
      - name: webapicore
    # enter the path to your image, be sure to include the correct region prefix    
        image: iad.ocir.io/idtz46tpaghv/webapicore:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: webapicore-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapicore